name: Daily Scrum
description: Daily Scrum report
title: "Daily-Scrum {{ date }}"
projects:
  - 281

body:
  - type: input
    id: start_at
    attributes:
      label: Start date
      default: "{{ date }}"

  - type: input
    id: end_at
    attributes:
      label: End date
      default: "{{ date }}"

  - type: markdown
    attributes:
      value: |
        {{ template: daily-scrum-template.md }}